-- Tracks shareable Stripe Checkout sessions generated by developers for financial officers.
-- A developer (who is authenticated) generates a checkout URL, sends it to the CFO,
-- and the CFO pays without needing a platform account.

CREATE TABLE IF NOT EXISTS billing_pending_checkout_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  stripe_session_id text UNIQUE NOT NULL,
  created_by_user_id uuid REFERENCES auth.users NOT NULL,
  tier_code text NOT NULL REFERENCES billing_tiers(tier_code),
  billing_period_months int NOT NULL,
  expires_at timestamptz NOT NULL,
  paid_at timestamptz,
  stripe_subscription_id text,
  created_at timestamptz DEFAULT now()
);

-- Developers can read their own pending sessions
ALTER TABLE billing_pending_checkout_sessions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read their own pending checkout sessions"
  ON billing_pending_checkout_sessions
  FOR SELECT
  USING (auth.uid() = created_by_user_id);

-- No direct insert/update from client — managed exclusively by edge functions via service role
