// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const USE_LOCAL = import.meta.env.VITE_USE_LOCAL_SUPABASE === 'true';

const LOCAL_URL = import.meta.env.VITE_SUPABASE_LOCAL_URL || 'http://127.0.0.1:54321';
const LOCAL_ANON_KEY = import.meta.env.VITE_SUPABASE_LOCAL_ANON_KEY || 'sb_publishable_ACJWlzQHlZjBrEguHvfOxg_3BJgxAaH';

const REMOTE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://fukzxedgbszcpakqkrjf.supabase.co';
const REMOTE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1a3p4ZWRnYnN6Y3Bha3FrcmpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MzIzMDQsImV4cCI6MjA2NjAwODMwNH0.sz4lyS_ljaJyFsxD0TKxcDTTDm0ovVg_uIAfilG6-GA';

const SUPABASE_URL = USE_LOCAL ? LOCAL_URL : REMOTE_URL;
const SUPABASE_PUBLISHABLE_KEY = USE_LOCAL ? LOCAL_ANON_KEY : REMOTE_ANON_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});